import { migratePlainTextToRichText } from '@/packages/base/AdRichText/richtext';
import type { Message } from '@/store/diary/type';

const base = {
  chatboxId: 'cb:dev',
  sender: 'user' as const,
  tagIds: [] as string[],
  pinned: true,
  archived: false,
  replyToMessageId: null as string | null,
  sourceMessageId: null as string | null,
  reactions: [] as Message['reactions'],
  edited: false,
  updatedAt: null as string | null,
};

export type PreviewCardFixture = {
  id: string;
  label: string;
  description: string;
  /** Expected Lucide IconId for quick visual audit */
  expectedIcon: string;
  message: Message;
};

export const PREVIEW_CARD_FIXTURES: PreviewCardFixture[] = [
  {
    id: 'todo',
    label: 'Variant · Todo',
    description: 'Todo variant, no attachments → no right preview',
    expectedIcon: 'ListTodo',
    message: {
      ...base,
      id: 'dev:todo',
      variant: 'todo',
      content: {
        items: [
          {
            id: 'todo:1',
            content: migratePlainTextToRichText('N5 Vocabulary'),
            completed: false,
            attachments: [],
          },
          {
            id: 'todo:2',
            content: migratePlainTextToRichText('N5 Grammar'),
            completed: false,
            attachments: [],
          },
        ],
      },
      attachments: [],
      decorators: [],
      createdAt: '2026-01-04T09:00:00.000Z',
    },
  },
  {
    id: 'ai',
    label: 'Variant · AI',
    description: 'AI variant with text only',
    expectedIcon: 'Sparkles',
    message: {
      ...base,
      id: 'dev:ai',
      variant: 'ai',
      content: migratePlainTextToRichText('Here is a study plan for JLPT N5 this week.'),
      attachments: [],
      decorators: [],
      createdAt: '2026-01-04T11:00:00.000Z',
    },
  },
  {
    id: 'timer',
    label: 'Decorator · Timer',
    description: 'Timer decorator, no attachments',
    expectedIcon: 'TimerReset',
    message: {
      ...base,
      id: 'dev:timer',
      variant: 'text',
      content: migratePlainTextToRichText('JLPT N5 Study Countdown'),
      attachments: [],
      decorators: [
        {
          type: 'timer',
          mode: 'timer',
          pause: true,
          running: false,
          durationMs: 12 * 60 * 60 * 1000 + 30 * 60 * 1000 + 45 * 1000,
          initialDurationMs: 12 * 60 * 60 * 1000 + 30 * 60 * 1000 + 45 * 1000,
          startedAt: null,
          targetDate: '2026-07-01T00:00:00.000Z',
          deadlineAt: null,
        },
      ],
      createdAt: '2026-01-04T10:24:00.000Z',
    },
  },
  {
    id: 'ticket',
    label: 'Decorator · Ticket',
    description: 'Ticket decorator, no attachments',
    expectedIcon: 'Ticket',
    message: {
      ...base,
      id: 'dev:ticket',
      variant: 'text',
      content: migratePlainTextToRichText('Review particle usage worksheet'),
      attachments: [],
      decorators: [
        {
          type: 'ticket',
          state: 'doing',
          ticked: false,
          placement: 'outside',
        },
      ],
      createdAt: '2026-01-05T08:30:00.000Z',
    },
  },
  {
    id: 'images',
    label: 'Attachment · Images',
    description: '5 images → Image + thumb + badge 5',
    expectedIcon: 'Image',
    message: {
      ...base,
      id: 'dev:images',
      variant: 'text',
      content: migratePlainTextToRichText('Mountain photos from our trip ...'),
      attachments: [
        {
          id: 'att:img-1',
          type: 'image',
          url: '/dummy/mountain-1.png',
          width: 1280,
          height: 720,
        },
        {
          id: 'att:img-2',
          type: 'image',
          url: '/dummy/mountain-2.png',
          width: 1280,
          height: 720,
        },
        {
          id: 'att:img-3',
          type: 'image',
          url: '/dummy/mountain-3.png',
          width: 1280,
          height: 720,
        },
        {
          id: 'att:img-4',
          type: 'image',
          url: '/dummy/mountain-4.png',
          width: 1280,
          height: 720,
        },
        {
          id: 'att:img-5',
          type: 'image',
          url: '/dummy/mountain-5.png',
          width: 1280,
          height: 720,
        },
      ],
      decorators: [],
      createdAt: '2026-01-05T10:30:00.000Z',
    },
  },
  {
    id: 'video',
    label: 'Attachment · Video',
    description: 'Single video attachment',
    expectedIcon: 'Video',
    message: {
      ...base,
      id: 'dev:video',
      variant: 'text',
      content: migratePlainTextToRichText('Listening practice clip'),
      attachments: [
        {
          id: 'att:video-1',
          type: 'video',
          url: '/dummy/listening.mp4',
          thumbnail: '/dummy/listening-thumb.png',
          duration: 95,
        },
      ],
      decorators: [],
      createdAt: '2026-01-05T12:00:00.000Z',
    },
  },
  {
    id: 'audio',
    label: 'Attachment · Audio',
    description: 'Audio file → Music icon + extension tile',
    expectedIcon: 'Music',
    message: {
      ...base,
      id: 'dev:audio',
      variant: 'text',
      content: migratePlainTextToRichText('Pronunciation drill recording'),
      attachments: [
        {
          id: 'att:audio-1',
          type: 'audio',
          url: '/dummy/drill.mp3',
          name: 'drill.mp3',
          mimeType: 'audio/mpeg',
          duration: 42,
        },
      ],
      decorators: [],
      createdAt: '2026-01-05T13:00:00.000Z',
    },
  },
  {
    id: 'document',
    label: 'Attachment · Document',
    description: '3 PDFs → NotepadText + .PDF tile + badge 3',
    expectedIcon: 'NotepadText',
    message: {
      ...base,
      id: 'dev:document',
      variant: 'text',
      content: migratePlainTextToRichText('Important Grammar Notes ...'),
      attachments: [
        {
          id: 'att:doc-1',
          type: 'document',
          url: '/dummy/grammar-notes.pdf',
          name: 'grammar-notes.pdf',
          mimeType: 'application/pdf',
        },
        {
          id: 'att:doc-2',
          type: 'document',
          url: '/dummy/particles.pdf',
          name: 'particles.pdf',
          mimeType: 'application/pdf',
        },
        {
          id: 'att:doc-3',
          type: 'document',
          url: '/dummy/verbs.pdf',
          name: 'verbs.pdf',
          mimeType: 'application/pdf',
        },
      ],
      decorators: [],
      createdAt: '2026-01-06T11:00:00.000Z',
    },
  },
  {
    id: 'note',
    label: 'Attachment · Note',
    description: 'Markdown / text note → CaseSensitive',
    expectedIcon: 'CaseSensitive',
    message: {
      ...base,
      id: 'dev:note',
      variant: 'text',
      content: migratePlainTextToRichText('Quick vocab dump'),
      attachments: [
        {
          id: 'att:note-1',
          type: 'note',
          url: '/dummy/vocab.md',
          name: 'vocab.md',
          mimeType: 'text/markdown',
        },
      ],
      decorators: [],
      createdAt: '2026-01-06T12:00:00.000Z',
    },
  },
  {
    id: 'archive',
    label: 'Attachment · Archive',
    description: 'Zip archive → Package',
    expectedIcon: 'Package',
    message: {
      ...base,
      id: 'dev:archive',
      variant: 'text',
      content: migratePlainTextToRichText('Backup of study sheets'),
      attachments: [
        {
          id: 'att:archive-1',
          type: 'archive',
          url: '/dummy/sheets.zip',
          name: 'sheets.zip',
          mimeType: 'application/zip',
        },
      ],
      decorators: [],
      createdAt: '2026-01-06T13:00:00.000Z',
    },
  },
  {
    id: 'code',
    label: 'Attachment · Code',
    description: 'TypeScript source → CodeXml',
    expectedIcon: 'CodeXml',
    message: {
      ...base,
      id: 'dev:code',
      variant: 'text',
      content: migratePlainTextToRichText('Anki sync helper script'),
      attachments: [
        {
          id: 'att:code-1',
          type: 'code',
          url: '/dummy/sync.ts',
          name: 'sync.ts',
          mimeType: 'text/typescript',
        },
      ],
      decorators: [],
      createdAt: '2026-01-06T14:00:00.000Z',
    },
  },
  {
    id: 'file-other',
    label: 'Attachment · Other file',
    description: 'Unknown binary → File catch-all',
    expectedIcon: 'File',
    message: {
      ...base,
      id: 'dev:file-other',
      variant: 'text',
      content: migratePlainTextToRichText('Exported deck binary'),
      attachments: [
        {
          id: 'att:file-other-1',
          type: 'file',
          url: '/dummy/deck.apkg',
          name: 'deck.apkg',
          mimeType: 'application/octet-stream',
        },
      ],
      decorators: [],
      createdAt: '2026-01-06T15:00:00.000Z',
    },
  },
  {
    id: 'link-og',
    label: 'Attachment · Link (OG preview)',
    description: 'Link with previewUrl → page thumbnail',
    expectedIcon: 'Link',
    message: {
      ...base,
      id: 'dev:link-og',
      variant: 'text',
      content: migratePlainTextToRichText('Useful Japanese Learning Resources'),
      attachments: [
        {
          id: 'att:link-1',
          type: 'link',
          url: 'https://www.jlpt.jp/e/',
          name: 'https://www.jlpt.jp/e/',
          previewUrl: 'https://picsum.photos/seed/jlpt-link/640/480',
          previewTitle: 'JLPT Official',
        },
        {
          id: 'att:link-2',
          type: 'link',
          url: 'https://jisho.org/',
          name: 'https://jisho.org/',
        },
      ],
      decorators: [],
      createdAt: '2026-01-07T14:20:00.000Z',
    },
  },
  {
    id: 'link-fallback',
    label: 'Attachment · Link (hostname fallback)',
    description: 'Link without previewUrl → hostname tile',
    expectedIcon: 'Link',
    message: {
      ...base,
      id: 'dev:link-fallback',
      variant: 'text',
      content: migratePlainTextToRichText('Dictionary bookmark'),
      attachments: [
        {
          id: 'att:link-only',
          type: 'link',
          url: 'https://jisho.org/',
          name: 'https://jisho.org/',
        },
      ],
      decorators: [],
      createdAt: '2026-01-07T15:00:00.000Z',
    },
  },
  {
    id: 'reply',
    label: 'Reply only',
    description: 'Text reply with no attachments/decorators',
    expectedIcon: 'MessageSquareReply',
    message: {
      ...base,
      id: 'dev:reply',
      variant: 'text',
      content: migratePlainTextToRichText('Sounds good — I will start tonight.'),
      attachments: [],
      decorators: [],
      replyToMessageId: 'dev:todo',
      createdAt: '2026-01-09T16:45:00.000Z',
    },
  },
  {
    id: 'normal',
    label: 'Normal message',
    description: 'Plain text fallback',
    expectedIcon: 'MessageCircleMore',
    message: {
      ...base,
      id: 'dev:normal',
      variant: 'text',
      content: migratePlainTextToRichText('Finished the vocabulary review! The focus timer helped me stay on track for the full session.'),
      attachments: [],
      decorators: [],
      pinned: false,
      archived: true,
      createdAt: '2026-06-09T10:30:00.000Z',
    },
  },
  {
    id: 'mixed-win-image',
    label: 'Edge · Mixed (images win)',
    description: '4 images + 1 video → image wins, badge 5',
    expectedIcon: 'Image',
    message: {
      ...base,
      id: 'dev:mixed-image',
      variant: 'text',
      content: migratePlainTextToRichText('Trip recap album and clip'),
      attachments: [
        { id: 'att:mx-1', type: 'image', url: '/dummy/trip-1.png' },
        { id: 'att:mx-2', type: 'image', url: '/dummy/trip-2.png' },
        { id: 'att:mx-3', type: 'image', url: '/dummy/trip-3.png' },
        { id: 'att:mx-4', type: 'image', url: '/dummy/trip-4.png' },
        { id: 'att:mx-v', type: 'video', url: '/dummy/trip.mp4' },
      ],
      decorators: [],
      createdAt: '2026-01-08T09:00:00.000Z',
    },
  },
  {
    id: 'long-title',
    label: 'Edge · Long title ellipsis',
    description: 'Very long title should truncate with ellipsis',
    expectedIcon: 'Image',
    message: {
      ...base,
      id: 'dev:long',
      variant: 'text',
      content: migratePlainTextToRichText('This is an intentionally very long message title so we can verify single-line ellipsis behavior on the preview card title row without wrapping into two lines'),
      attachments: [
        {
          id: 'att:long-img',
          type: 'image',
          url: '/dummy/long-title.png',
        },
      ],
      decorators: [],
      createdAt: '2026-01-10T18:00:00.000Z',
    },
  },
];
